### ISSUE TITLE
Remove credentials from github

### ISSUE THREAD

**Issue by vdias38** [meumobi/AMS.Report#10]
### Actual behaviour
on cf and src code there are references to firebase credentials, should remove them. Migrate data to gDrive Settings and Credentials docs.

**Comment by danconte72** [comment]
- [x] modify the commit adding int config data following these [steps](http://meumobi.github.io/git/2015/08/03/useful-git-commands.html#how-to-modify-a-specified-commit-)

**Comment by danconte72** [comment]
Closed on https://github.com/meumobi/AMS.Report/commit/8d9587f62a2dc0a39ee42d4cf6e43b24143ce518 
rebase
