### ISSUE TITLE
can't retrieve all entries, freeze browser

### ISSUE THREAD

**Issue by vdias38** [meumobi/AMS.Report#9]
### Expected behaviour
Tell us what should happen

### Actual behaviour

![sites](https://user-images.githubusercontent.com/9011612/50239465-2325f000-03ba-11e9-8d56-c21b2776747b.png)

### Steps to reproduce
1. log in as admin
2. select reporting menu link
3. the report freeze and browser memory increase

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
On reproducing the error:
```
vendor.js:1 FIREBASE WARNING: Using an unspecified index. Your data will be downloaded and filtered on the client. Consider adding ".indexOn": "date" at /reports to your security rules for better performance.
```

**Comment by danconte72** [comment]
I've update database rules to 
```js
{
  "rules": {
      ".read": "auth !== null",
      ".write": "auth !== null",
      "reports": {
        ".indexOn": ["group", "date"]
      }
   }
}
```
And freeze it not happens again
